# Generated by Django 3.2.9 on 2022-05-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_locations_address'),
        ('generics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
