# Generated by Django 4.0.5 on 2022-06-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_training_city'),
        ('cv', '0006_remove_emplocations_city'),
        ('jobs', '0007_remove_locations_city'),
        ('generics', '0002_delete_addresses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
