# Generated by Django 3.2.9 on 2022-05-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0001_initial'),
        ('jobs', '0003_auto_20220512_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.skills'),
        ),
    ]
