# Generated by Django 3.2.9 on 2022-06-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_locations_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='heading',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(max_length=110),
        ),
    ]
