# Generated by Django 3.2.9 on 2022-04-19 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(upload_to='cv/')),
                ('interests', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.grades')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.skills')),
            ],
        ),
        migrations.CreateModel(
            name='EmpPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
            ],
        ),
        migrations.CreateModel(
            name='EmpLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.addresses')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.cities')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.countries')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
            ],
        ),
        migrations.CreateModel(
            name='EmpExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.experiences')),
            ],
        ),
        migrations.CreateModel(
            name='EmpEducations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.educations')),
            ],
        ),
    ]
