# Generated by Django 3.2.9 on 2022-05-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0001_initial'),
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empeducations',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.educations', unique=True),
        ),
        migrations.AlterField(
            model_name='empexperience',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.experiences', unique=True),
        ),
        migrations.AlterField(
            model_name='empskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics.skills', unique=True),
        ),
    ]
